version: "3.9"

networks:
  internet:
    external: true

services:
  traefik:
    image: library/traefik:latest
    container_name: traefik
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - ./.novi/hosting/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.services.traefik.loadbalancer.server.port=8042"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=chain-no-auth@file"

  mysql:
    image: library/mariadb:10.6
    container_name: mysql
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --default-authentication-plugin=mysql_native_password,
        --max_allowed_packet=512M,
        --innodb_buffer_pool_size=1G,
        --innodb_log_file_size=1G,
        --innodb_log_buffer_size=1G,
        --max_connections=1000
      ]
    volumes:
      - ./.novi/hosting/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    networks:
      - internet
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  redis:
    image: library/redis:latest
    container_name: redis
    volumes:
    - ./.novi/hosting/data/redis:/data
    - ./.novi/hosting/redis.conf:/etc/redis/redis.conf
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    networks:
      - internet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 10
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=cloudflare"
      - "traefik.http.services.nginx.loadbalancer.server.port=8080"
      - "traefik.http.routers.nginx.middlewares=web,chain-no-auth@file"
      - "traefik.http.middlewares.nginx.headers.stsSeconds=155520011"
      - "traefik.http.middlewares.nginx.headers.stsPreload=true"
      - "traefik.http.middlewares.nginx.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.nginx.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.chain-redirect-to-https.redirectscheme.scheme=https"
    image: sahistory/nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./.novi/hosting/data/web/private:/app/private
      - ./.novi/hosting/data/web/files:/app/webroot/sites/${WEBROOT_SITE}/files
    networks:
      - internet
    depends_on:
      - traefik

  phpfpm:
    labels:
      - "ofelia.enabled=true"
      - "ofelia.job-exec.drupal.user=0"
      - "ofelia.job-exec.drupal.schedule=@every 1m"
      - "ofelia.job-exec.drupal.command=/usr/bin/php /app/vendor/drush/drush/drush -l ${WEBROOT_SITE} core:cron"
    image: sahistory/fpm:latest
    container_name: phpfpm
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./.novi/hosting/data/web/private:/app/private
      - ./.novi/hosting/data/web/files:/app/webroot/sites/${WEBROOT_SITE}/files
      - ./.novi/hosting/data/web/logs:/app/logs
      - ./.novi/dbdumps:/app/.novi/dbdumps
      - ./.novi/backups:/app/.novi/backups
    env_file:
      - .env
    environment:
      PHP_MEMORY_LIMIT: 1024M
      WEBROOT_SITE: ${WEBROOT_SITE}
      DOMAIN: ${DOMAIN_NAME}
      TRUSTED_HOST_PATTERNS: ${TRUSTED_HOST_PATTERNS}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      HASH_SALT: ${HASH_SALT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
    networks:
      - internet
    depends_on:
      - nginx
      - redis
      - mysql

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    restart: unless-stopped
    command: daemon --docker
    networks:
      - internet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - phpfpm
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  solr:
    image: solr:8.11.2
    container_name: solr
    ports:
     - "8983:8983"
    volumes:
      - ./.novi/hosting/data/solr:/var/solr
      - ./.novi/hosting/solr:/opt/solr/server/solr/saho
    restart: unless-stopped
    depends_on:
      - phpfpm
    networks:
      - internet
