<?php

/**
 * @file
 * Provides a submodule to display featured biographies under SAHO Utilities.
 */

/**
 * Implements hook_theme().
 */
function featured_biography_theme($existing, $type, $theme, $path) {
  return [
    'featured_biography_block' => [
      'variables' => [
        'biography_item' => NULL,
        'display_mode' => 'full',
      ],
      'template' => 'featured-biography-block',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for featured_biography_block templates.
 */
function featured_biography_preprocess_featured_biography_block(&$variables) {
  // Attach the featured biography library.
  $variables['#attached']['library'][] = 'featured_biography/featured-biography';
}