<?php

/**
 * @file
 * SAHO Donate module hooks.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function saho_donate_theme(): array {
  return [
    'saho_donate_page' => [
      'variables' => [
        'form' => NULL,
      ],
    ],
    'saho_donate_redirect' => [
      'variables' => [
        'payfast_url' => '',
        'fields' => [],
      ],
    ],
    'saho_donate_thankyou' => [
      'variables' => [],
    ],
  ];
}
