<?php

/**
 * @file
 * SAHO Classroom - self-contained deck renderer (issue #436).
 *
 * Pure PHP with no Drupal bootstrap. Reads a slide-schema JSON file (see
 * schema/slide-schema.json) and emits a single, fully self-contained HTML deck
 * with the engine CSS and JS inlined. The output makes zero external requests
 * (no CDN, fonts, scripts or remote images), opens from file:// offline, and
 * reproduces the prototype's UX and accessibility.
 *
 * CLI usage:
 *   php render.php path/to/deck.json > out.html
 *   php render.php path/to/deck.json out.html
 *
 * Library usage:
 *   require_once 'render.php';
 *   $html = saho_classroom_render_deck_file('deck.json');
 *   // or, from a decoded array:
 *   $html = saho_classroom_render_deck($deck_array);
 *
 * Deliberately dependency-free so the same routine can run in a CI check, a
 * Drush command, or a build step without pulling in the Drupal container.
 */

declare(strict_types=1);

/**
 * Renders a deck JSON file to a self-contained HTML string.
 *
 * @param string $json_path
 *   Absolute or relative path to a slide-schema JSON file.
 *
 * @return string
 *   The rendered, self-contained HTML document.
 *
 * @throws \RuntimeException
 *   When the file cannot be read or contains invalid JSON.
 */
function saho_classroom_render_deck_file(string $json_path): string {
  if (!is_file($json_path) || !is_readable($json_path)) {
    throw new \RuntimeException("Cannot read deck file: {$json_path}");
  }
  $raw = file_get_contents($json_path);
  if ($raw === FALSE) {
    throw new \RuntimeException("Failed to read deck file: {$json_path}");
  }
  try {
    $deck = json_decode($raw, TRUE, 512, JSON_THROW_ON_ERROR);
  }
  catch (\JsonException $e) {
    throw new \RuntimeException("Invalid JSON in {$json_path}: " . $e->getMessage(), 0, $e);
  }
  if (!is_array($deck)) {
    throw new \RuntimeException("Deck JSON must be an object: {$json_path}");
  }
  return saho_classroom_render_deck($deck);
}

/**
 * Renders a decoded deck array to a self-contained HTML string.
 *
 * @param array $deck
 *   The decoded slide-schema structure (meta + slides).
 * @param string|null $css
 *   Optional engine CSS override. Defaults to engine/deck.css beside this file.
 * @param string|null $js
 *   Optional engine JS override. Defaults to engine/deck.js beside this file.
 *
 * @return string
 *   The rendered, self-contained HTML document.
 */
function saho_classroom_render_deck(array $deck, ?string $css = NULL, ?string $js = NULL): string {
  $meta = isset($deck['meta']) && is_array($deck['meta']) ? $deck['meta'] : [];
  $slides = isset($deck['slides']) && is_array($deck['slides']) ? array_values($deck['slides']) : [];
  if (!$slides) {
    throw new \RuntimeException('Deck has no slides.');
  }

  $css = $css ?? saho_classroom_engine_asset('deck.css');
  $js = $js ?? saho_classroom_engine_asset('deck.js');

  $total = count($slides);
  $title = (string) ($meta['title'] ?? 'Presentation');
  $subject = trim((string) ($meta['subject'] ?? ''));
  $grade = trim((string) ($meta['grade'] ?? ''));
  $lang = trim((string) ($meta['language'] ?? 'en')) ?: 'en';

  // Human context string used for the document title and the deck aria-label.
  $context_parts = [];
  if ($grade !== '') {
    $context_parts[] = 'Grade ' . $grade;
  }
  if ($subject !== '') {
    $context_parts[] = $subject;
  }
  $context = $context_parts ? implode(' ', $context_parts) : '';
  $doc_title = $title . ' - SAHO Classroom' . ($context !== '' ? " ({$context})" : '');
  $deck_label = $title . ($context !== '' ? ", {$context}" : '');

  $description = trim((string) ($meta['attribution'] ?? ''));
  if ($description === '') {
    $description = "SAHO Classroom presentation: {$title}.";
  }

  // Render the slide sections.
  $sections = [];
  foreach ($slides as $i => $slide) {
    $sections[] = saho_classroom_render_slide(is_array($slide) ? $slide : [], (int) $i, $total, $meta);
  }
  $slides_html = implode("\n", $sections);

  $e = 'saho_classroom_e';

  return '<!doctype html>' . "\n"
    . '<html lang="' . $e($lang) . '">' . "\n"
    . "<head>\n"
    . '<meta charset="utf-8">' . "\n"
    . '<meta name="viewport" content="width=device-width, initial-scale=1">' . "\n"
    . '<title>' . $e($doc_title) . "</title>\n"
    . '<meta name="description" content="' . $e($description) . '">' . "\n"
    . "<!--\n"
    . "  SAHO Classroom deck - generated by presentation/render.php (issue #436).\n"
    . "  Self-contained: all CSS and JS are inline and imagery is inline SVG or a\n"
    . "  data: URI. No external CDN, fonts, scripts or image URLs, so this deck\n"
    . "  opens from file:// offline and makes zero external requests.\n"
    . "-->\n"
    . "<style>\n" . $css . "\n</style>\n"
    . "</head>\n"
    . "<body>\n"
    . '<a class="skip-link" href="#slide-1">Skip to lesson content</a>' . "\n\n"
    . '<div class="deck" id="deck" role="application" aria-roledescription="slide presentation" aria-label="' . $e($deck_label) . '">' . "\n"
    . '  <div class="progress" id="progress" aria-hidden="true"></div>' . "\n\n"
    . '  <div class="deck__stage" id="stage">' . "\n\n"
    . '    <p class="visually-hidden" id="live" aria-live="polite"></p>' . "\n\n"
    . $slides_html . "\n\n"
    . saho_classroom_edge_and_dots()
    . '  </div>' . "\n\n"
    . '  <aside class="notes" id="notesPanel" aria-live="polite" aria-label="Speaker notes for the current slide"></aside>' . "\n\n"
    . saho_classroom_toolbar($total)
    . '</div>' . "\n\n"
    . "<script>\n" . $js . "\n</script>\n"
    . "</body>\n"
    . "</html>\n";
}

/**
 * Reads an engine asset (deck.css / deck.js) from beside this file.
 *
 * @param string $name
 *   Asset filename.
 *
 * @return string
 *   File contents.
 *
 * @throws \RuntimeException
 *   When the asset is missing.
 */
function saho_classroom_engine_asset(string $name): string {
  $path = __DIR__ . '/engine/' . $name;
  if (!is_file($path)) {
    throw new \RuntimeException("Missing engine asset: {$path}");
  }
  $data = file_get_contents($path);
  if ($data === FALSE) {
    throw new \RuntimeException("Failed to read engine asset: {$path}");
  }
  return rtrim($data);
}

/**
 * Renders a single slide <section>.
 *
 * @param array $slide
 *   The slide structure.
 * @param int $index
 *   Zero-based slide index.
 * @param int $total
 *   Total slide count.
 * @param array $meta
 *   Lesson metadata (used for the title slide's pills and attribution).
 *
 * @return string
 *   The slide HTML.
 */
function saho_classroom_render_slide(array $slide, int $index, int $total, array $meta): string {
  $e = 'saho_classroom_e';
  $num = $index + 1;

  // Field aliases: type|layout, heading|title, image|media.
  $type = (string) ($slide['type'] ?? $slide['layout'] ?? 'content');
  $heading = (string) ($slide['heading'] ?? $slide['title'] ?? '');
  $eyebrow = (string) ($slide['eyebrow'] ?? '');
  $lead = (string) ($slide['lead'] ?? '');
  $image = $slide['image'] ?? $slide['media'] ?? NULL;

  $id = (string) ($slide['id'] ?? '');
  // Anchor id is always slide-N so deep links and the skip link stay stable.
  $anchor = 'slide-' . $num;

  $is_title = ($type === 'title');
  $label_suffix = $heading !== '' ? ': ' . $heading : '';
  $classes = 'slide' . ($is_title ? ' title-slide' : '');

  $inner = [];

  if ($eyebrow !== '') {
    $inner[] = '      <span class="slide__eyebrow">' . saho_classroom_inline($eyebrow) . '</span>';
  }
  if ($heading !== '') {
    $tag = $is_title ? 'h1' : 'h2';
    $inner[] = "      <{$tag}>" . saho_classroom_inline($heading) . "</{$tag}>";
  }
  if ($lead !== '') {
    $inner[] = '      <p class="lead">' . saho_classroom_inline($lead) . '</p>';
  }
  if (!empty($slide['body']) && is_string($slide['body'])) {
    $inner[] = saho_classroom_paragraphs($slide['body'], '      ');
  }
  if (!empty($slide['bullets']) && is_array($slide['bullets'])) {
    $inner[] = saho_classroom_render_list($slide['bullets'], FALSE, '      ');
  }

  // Two-column layout via explicit columns.
  if (!empty($slide['columns']) && is_array($slide['columns'])) {
    $inner[] = saho_classroom_render_columns($slide['columns']);
  }
  // Blocks: for cards / two-column types with card-like blocks, wrap in a grid.
  elseif (!empty($slide['blocks']) && is_array($slide['blocks'])) {
    $blocks_html = saho_classroom_render_blocks($slide['blocks'], '        ');
    if ($type === 'cards' || $type === 'two-column') {
      $inner[] = '      <div class="cols">' . "\n" . $blocks_html . "\n" . '      </div>';
    }
    else {
      $inner[] = $blocks_html;
    }
  }

  if ($image !== NULL && is_array($image)) {
    $fig = saho_classroom_render_image($image, '      ');
    if ($fig !== '') {
      $inner[] = $fig;
    }
  }

  // Title slide: metadata pills + attribution line.
  if ($is_title) {
    $pills = saho_classroom_meta_pills($meta);
    if ($pills !== '') {
      $inner[] = $pills;
    }
    $attribution = trim((string) ($meta['attribution'] ?? ''));
    if ($attribution !== '') {
      $inner[] = '      <p class="muted" style="margin-top:1.6rem;">' . saho_classroom_inline($attribution) . '</p>';
    }
  }

  // Sources appear on the closing summary slide when present.
  if ($type === 'summary' && !empty($meta['sources']) && is_array($meta['sources'])) {
    $inner[] = saho_classroom_render_sources($meta['sources']);
  }

  // Speaker notes.
  if (!empty($slide['notes']) && is_string($slide['notes'])) {
    $inner[] = saho_classroom_render_notes($slide['notes']);
  }

  $inner_html = implode("\n", array_filter($inner, static fn($p) => $p !== ''));

  $label = 'Slide ' . $num . ' of ' . $total . $label_suffix;

  return '    <section class="' . $classes . '" id="' . $e($anchor) . '"'
    . ($id !== '' ? ' data-slide-id="' . $e($id) . '"' : '')
    . ' role="group" aria-roledescription="slide" aria-label="' . $e($label) . '">' . "\n"
    . $inner_html . "\n"
    . '    </section>';
}

/**
 * Renders the lesson metadata pills for the title slide.
 */
function saho_classroom_meta_pills(array $meta): string {
  $pills = [];
  $subject = trim((string) ($meta['subject'] ?? ''));
  $grade = trim((string) ($meta['grade'] ?? ''));
  $phase = trim((string) ($meta['phase'] ?? ''));
  $topic = trim((string) ($meta['caps_topic'] ?? ''));
  $duration = $meta['duration_minutes'] ?? NULL;

  if ($subject !== '') {
    $pills[] = '<span class="pill">Subject: ' . saho_classroom_e($subject) . '</span>';
  }
  if ($grade !== '' || $phase !== '') {
    $label = trim(($grade !== '' ? 'Grade ' . $grade : '') . ($grade !== '' && $phase !== '' ? ' - ' : '') . ($phase !== '' ? $phase . ' Phase' : ''));
    $pills[] = '<span class="pill pill--green">' . saho_classroom_e($label) . '</span>';
  }
  if ($topic !== '') {
    $pills[] = '<span class="pill pill--gold">CAPS: ' . saho_classroom_e($topic) . '</span>';
  }
  if (is_numeric($duration) && (int) $duration > 0) {
    $pills[] = '<span class="pill">Duration: ~' . (int) $duration . ' min</span>';
  }
  if (!$pills) {
    return '';
  }
  return '      <div class="meta">' . "\n        " . implode("\n        ", $pills) . "\n      </div>";
}

/**
 * Renders a list of source citations.
 */
function saho_classroom_render_sources(array $sources): string {
  $items = [];
  foreach ($sources as $source) {
    if (!is_array($source)) {
      continue;
    }
    if (!empty($source['citation'])) {
      $items[] = saho_classroom_inline((string) $source['citation']);
      continue;
    }
    $parts = [];
    if (!empty($source['author'])) {
      $parts[] = saho_classroom_e((string) $source['author']);
    }
    if (!empty($source['title'])) {
      $parts[] = '<em>' . saho_classroom_e((string) $source['title']) . '</em>';
    }
    if (!empty($source['url'])) {
      // URL shown as text only; never fetched, so the deck stays self-contained.
      $parts[] = saho_classroom_e((string) $source['url']);
    }
    if ($parts) {
      $items[] = implode('. ', $parts);
    }
  }
  if (!$items) {
    return '';
  }
  $lis = array_map(static fn($t) => '        <li>' . $t . '</li>', $items);
  return '      <h3>Sources</h3>' . "\n"
    . '      <ul class="muted">' . "\n" . implode("\n", $lis) . "\n      </ul>";
}

/**
 * Renders the two-column layout from explicit column block lists.
 */
function saho_classroom_render_columns(array $columns): string {
  $cols = [];
  foreach ($columns as $blocks) {
    if (!is_array($blocks)) {
      continue;
    }
    $cols[] = '        <div>' . "\n" . saho_classroom_render_blocks($blocks, '          ') . "\n        </div>";
  }
  if (!$cols) {
    return '';
  }
  return '      <div class="cols">' . "\n" . implode("\n", $cols) . "\n      </div>";
}

/**
 * Renders an ordered list of content blocks.
 */
function saho_classroom_render_blocks(array $blocks, string $indent = '      '): string {
  $out = [];
  foreach ($blocks as $block) {
    if (!is_array($block)) {
      continue;
    }
    $html = saho_classroom_render_block($block, $indent);
    if ($html !== '') {
      $out[] = $html;
    }
  }
  return implode("\n", $out);
}

/**
 * Renders a single content block.
 */
function saho_classroom_render_block(array $block, string $indent = '      '): string {
  $type = (string) ($block['type'] ?? '');
  switch ($type) {
    case 'paragraph':
      return saho_classroom_paragraphs((string) ($block['text'] ?? ''), $indent);

    case 'list':
      $items = is_array($block['items'] ?? NULL) ? $block['items'] : [];
      return saho_classroom_render_list($items, !empty($block['ordered']), $indent);

    case 'heading':
      $level = (int) ($block['level'] ?? 3);
      $level = max(2, min(4, $level));
      return $indent . "<h{$level}>" . saho_classroom_inline((string) ($block['text'] ?? '')) . "</h{$level}>";

    case 'card':
      $card = $indent . '<div class="card">' . "\n";
      if (!empty($block['heading'])) {
        $card .= $indent . '  <h3>' . saho_classroom_inline((string) $block['heading']) . '</h3>' . "\n";
      }
      $card .= $indent . '  <p>' . saho_classroom_inline((string) ($block['text'] ?? '')) . '</p>' . "\n";
      $card .= $indent . '</div>';
      return $card;

    case 'quote':
      $q = $indent . '<blockquote>' . "\n"
        . $indent . '  ' . saho_classroom_inline((string) ($block['text'] ?? '')) . "\n";
      if (!empty($block['cite'])) {
        $q .= $indent . '  <cite>' . saho_classroom_inline((string) $block['cite']) . '</cite>' . "\n";
      }
      $q .= $indent . '</blockquote>';
      return $q;

    case 'timeline':
      $events = is_array($block['events'] ?? NULL) ? $block['events'] : [];
      return saho_classroom_render_timeline($events, (string) ($block['alt'] ?? ''), (string) ($block['caption'] ?? ''), $indent);

    case 'qa':
      $label = trim((string) ($block['label'] ?? ''));
      $marks = $block['marks'] ?? NULL;
      $q = $indent . '<div class="qa">' . "\n" . $indent . '  <p>';
      if ($label !== '') {
        $q .= '<b>' . saho_classroom_e($label) . '</b> ';
      }
      $q .= saho_classroom_inline((string) ($block['question'] ?? ''));
      if (is_numeric($marks)) {
        $q .= ' (' . (int) $marks . ' marks)';
      }
      $q .= '</p>' . "\n" . $indent . '</div>';
      return $q;

    case 'image':
      return saho_classroom_render_image($block, $indent);

    default:
      return '';
  }
}

/**
 * Renders an unordered or ordered list.
 */
function saho_classroom_render_list(array $items, bool $ordered, string $indent = '      '): string {
  $items = array_values(array_filter($items, static fn($i) => is_string($i) && $i !== ''));
  if (!$items) {
    return '';
  }
  $tag = $ordered ? 'ol' : 'ul';
  $lis = array_map(static fn($i) => $indent . '  <li>' . saho_classroom_inline($i) . '</li>', $items);
  return $indent . "<{$tag}>\n" . implode("\n", $lis) . "\n" . $indent . "</{$tag}>";
}

/**
 * Renders a figure from an image block/object.
 *
 * Accepts inline SVG markup or a data: URI only. External URLs are dropped to
 * keep the deck self-contained; a warning is written to stderr.
 */
function saho_classroom_render_image(array $image, string $indent = '      '): string {
  $data = (string) ($image['data'] ?? '');
  if ($data === '') {
    return '';
  }
  $alt = (string) ($image['alt'] ?? '');
  $caption = (string) ($image['caption'] ?? '');
  $trimmed = ltrim($data);

  $body = '';
  if (stripos($trimmed, '<svg') === 0 || stripos($trimmed, '<?xml') === 0) {
    // Trusted inline SVG authored in the schema: embed as-is.
    $body = $trimmed;
  }
  elseif (stripos($trimmed, 'data:') === 0) {
    $body = '<img src="' . saho_classroom_e($trimmed) . '" alt="' . saho_classroom_e($alt) . '">';
  }
  else {
    saho_classroom_warn("Dropping non-self-contained image (not inline SVG or data: URI): " . substr($data, 0, 60));
    return '';
  }

  $out = $indent . '<figure class="figure">' . "\n" . $indent . '  ' . $body . "\n";
  if ($caption !== '') {
    $out .= $indent . '  <figcaption>' . saho_classroom_inline($caption) . '</figcaption>' . "\n";
  }
  $out .= $indent . '</figure>';
  return $out;
}

/**
 * Generates an accessible inline-SVG timeline from year/label events.
 */
function saho_classroom_render_timeline(array $events, string $alt, string $caption, string $indent = '      '): string {
  $events = array_values(array_filter($events, static fn($ev) => is_array($ev) && isset($ev['year'], $ev['label'])));
  $n = count($events);
  if ($n === 0) {
    return '';
  }

  static $seq = 0;
  $seq++;
  $tid = 'tl-title-' . $seq;
  $did = 'tl-desc-' . $seq;

  $palette = ['#990000', '#b88a2e', '#990000', '#2d5016', '#3a4a64'];
  $text_palette = ['#7a0000', '#8a6a1e', '#7a0000', '#2d5016', '#3a4a64'];

  $x0 = 120;
  $x1 = 900;
  $span = ($n > 1) ? ($x1 - $x0) / ($n - 1) : 0;

  if ($alt === '') {
    $labels = array_map(static fn($ev) => $ev['year'] . ' ' . $ev['label'], $events);
    $alt = 'Timeline: ' . implode('; ', $labels) . '.';
  }
  $title_text = 'Timeline';

  $svg = $indent . '  <svg viewBox="0 0 1000 240" role="img" aria-labelledby="' . $tid . ' ' . $did . '">' . "\n";
  $svg .= $indent . '    <title id="' . $tid . '">' . saho_classroom_e($title_text) . '</title>' . "\n";
  $svg .= $indent . '    <desc id="' . $did . '">' . saho_classroom_e($alt) . '</desc>' . "\n";
  $svg .= $indent . '    <line x1="60" y1="120" x2="940" y2="120" stroke="#3a4a64" stroke-width="4"/>' . "\n";
  $svg .= $indent . '    <g font-family="sans-serif" text-anchor="middle">' . "\n";
  foreach ($events as $i => $ev) {
    $cx = (int) round($x0 + $span * $i);
    $fill = $palette[$i % count($palette)];
    $tfill = $text_palette[$i % count($text_palette)];
    $year = saho_classroom_e((string) $ev['year']);
    $label = saho_classroom_e((string) $ev['label']);
    $svg .= $indent . '      <circle cx="' . $cx . '" cy="120" r="12" fill="' . $fill . '"/>' . "\n";
    $svg .= $indent . '      <text x="' . $cx . '" y="90" font-size="22" font-weight="700" fill="' . $tfill . '">' . $year . '</text>' . "\n";
    $svg .= $indent . '      <text x="' . $cx . '" y="168" font-size="15" fill="#1e293b">' . $label . '</text>' . "\n";
  }
  $svg .= $indent . '    </g>' . "\n";
  $svg .= $indent . '  </svg>' . "\n";

  $out = $indent . '<figure class="figure">' . "\n" . $svg;
  if ($caption !== '') {
    $out .= $indent . '  <figcaption>' . saho_classroom_inline($caption) . '</figcaption>' . "\n";
  }
  $out .= $indent . '</figure>';
  return $out;
}

/**
 * Renders the speaker-notes block (Markdown paragraphs).
 */
function saho_classroom_render_notes(string $notes): string {
  $paras = saho_classroom_split_paragraphs($notes);
  if (!$paras) {
    return '';
  }
  $out = '      <div class="notes" data-notes>' . "\n";
  $out .= '        <h4>Speaker notes</h4>' . "\n";
  foreach ($paras as $p) {
    $out .= '        <p>' . saho_classroom_inline($p) . '</p>' . "\n";
  }
  $out .= '      </div>';
  return $out;
}

/**
 * Renders a body string into one or more <p> paragraphs.
 */
function saho_classroom_paragraphs(string $text, string $indent = '      '): string {
  $paras = saho_classroom_split_paragraphs($text);
  if (!$paras) {
    return '';
  }
  $out = array_map(static fn($p) => $indent . '<p>' . saho_classroom_inline($p) . '</p>', $paras);
  return implode("\n", $out);
}

/**
 * Splits text into paragraphs on blank lines.
 *
 * @return string[]
 *   Non-empty paragraph strings with internal single newlines collapsed.
 */
function saho_classroom_split_paragraphs(string $text): array {
  $text = str_replace(["\r\n", "\r"], "\n", $text);
  $chunks = preg_split('/\n{2,}/', trim($text));
  $paras = [];
  foreach ($chunks as $chunk) {
    $chunk = trim(preg_replace('/\s*\n\s*/', ' ', $chunk));
    if ($chunk !== '') {
      $paras[] = $chunk;
    }
  }
  return $paras;
}

/**
 * Escapes text for safe HTML output.
 */
function saho_classroom_e(string $value): string {
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * Escapes text and applies a tiny, safe inline-Markdown subset.
 *
 * Supports **bold**, *italic*, `code`, and [text](url) with an http(s), mailto
 * or in-page (#) scheme. Everything is HTML-escaped first, so no author markup
 * can inject tags; only these known patterns are re-introduced as elements.
 */
function saho_classroom_inline(string $text): string {
  $out = saho_classroom_e($text);

  // Inline code first, so its contents are not further transformed.
  $out = preg_replace_callback('/`([^`]+)`/', static function ($m) {
    return '<code>' . $m[1] . '</code>';
  }, $out);

  // Links: [text](url). URL was escaped, so &amp; etc. are already safe.
  $out = preg_replace_callback('/\[([^\]]+)\]\(([^)\s]+)\)/', static function ($m) {
    $label = $m[1];
    $url = $m[2];
    // Only allow safe schemes; reject javascript: and friends.
    if (!preg_match('~^(https?:|mailto:|#|/|\.)~i', html_entity_decode($url, ENT_QUOTES, 'UTF-8'))) {
      return $label;
    }
    return '<a href="' . $url . '">' . $label . '</a>';
  }, $out);

  // Bold before italic so ** is not eaten by the single-* rule.
  $out = preg_replace('/\*\*([^*]+)\*\*/', '<strong>$1</strong>', $out);
  $out = preg_replace('/(?<!\*)\*([^*\n]+)\*(?!\*)/', '<em>$1</em>', $out);

  return $out;
}

/**
 * Writes a warning to stderr (CLI) without breaking the emitted HTML on stdout.
 */
function saho_classroom_warn(string $message): void {
  if (PHP_SAPI === 'cli' && defined('STDERR')) {
    fwrite(STDERR, "warning: {$message}\n");
  }
}

// ---------------------------------------------------------------------------
// Static DOM fragments (edge arrows, dots, hint, toolbar) matching the
// prototype. Kept as functions so the markup lives with the renderer.
// ---------------------------------------------------------------------------

/**
 * Edge navigation arrows, progress dots container and keyboard hint.
 */
function saho_classroom_edge_and_dots(): string {
  return <<<HTML
    <button class="edge edge--prev" id="prev" type="button" aria-label="Previous slide">
      <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 4l-8 8 8 8" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
    </button>
    <button class="edge edge--next" id="next" type="button" aria-label="Next slide">
      <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 4l8 8-8 8" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
    </button>

    <div class="dots" id="dots" role="tablist" aria-label="Slide navigation"></div>

    <div class="hint" id="hint" role="note">
      Use <kbd>&larr;</kbd> <kbd>&rarr;</kbd> to move &middot; <kbd>F</kbd> present &middot; <kbd>S</kbd> notes &middot; <kbd>P</kbd> print
    </div>

HTML;
}

/**
 * The bottom control toolbar.
 */
function saho_classroom_toolbar(int $total): string {
  $total_e = (int) $total;
  return <<<HTML
  <div class="toolbar" role="toolbar" aria-label="Presentation controls">
    <span class="brand"><span class="mark">SA</span> SAHO Classroom <small>HTML deck</small></span>
    <button class="btn btn--icon" id="btnPrev" type="button" aria-label="Previous slide">&larr;</button>
    <span class="counter" id="counter" aria-hidden="true">1 / {$total_e}</span>
    <button class="btn btn--icon" id="btnNext" type="button" aria-label="Next slide">&rarr;</button>
    <button class="btn" id="btnNotes" type="button" aria-pressed="false">Notes <span class="visually-hidden">(S)</span></button>
    <button class="btn" id="btnFull" type="button" aria-pressed="false">Present <span class="visually-hidden">fullscreen (F)</span></button>
    <button class="btn" id="btnPrint" type="button">Print / PDF <span class="visually-hidden">(P)</span></button>
  </div>

HTML;
}

// ---------------------------------------------------------------------------
// CLI entry point. No-op when this file is require()'d as a library.
// ---------------------------------------------------------------------------
if (PHP_SAPI === 'cli' && isset($argv[0]) && realpath($argv[0]) === realpath(__FILE__)) {
  $in = $argv[1] ?? '';
  if ($in === '' || in_array($in, ['-h', '--help'], TRUE)) {
    fwrite(STDERR, "SAHO Classroom deck renderer\n\n");
    fwrite(STDERR, "Usage: php render.php <schema.json> [out.html]\n");
    fwrite(STDERR, "       php render.php <schema.json> > out.html\n");
    exit($in === '' ? 1 : 0);
  }
  try {
    $html = saho_classroom_render_deck_file($in);
  }
  catch (\Throwable $err) {
    fwrite(STDERR, 'error: ' . $err->getMessage() . "\n");
    exit(1);
  }
  $out = $argv[2] ?? '';
  if ($out !== '') {
    if (file_put_contents($out, $html) === FALSE) {
      fwrite(STDERR, "error: failed to write {$out}\n");
      exit(1);
    }
    fwrite(STDERR, "wrote {$out}\n");
  }
  else {
    fwrite(STDOUT, $html);
  }
  exit(0);
}
