<?php

/**
 * @file
 * Contains hook implementations for SAHO Media Migration module.
 */

/**
 * Implements hook_help().
 */
function saho_media_migration_help($route_name, $route_parameters) {
  switch ($route_name) {
    case 'help.page.saho_media_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The SAHO Media Migration module provides tools for migrating file entities to media entities.') . '</p>';
      return $output;
  }
}