name: Bug report
description: Report something that isn't working as expected
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## 🐛 Bug Report — Thank you for improving SAHO!"

  - type: input
    id: url
    attributes:
      label: URL (if applicable)
      description: Link to the affected page
      placeholder: "https://www.sahistory.org.za/page/example"

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
  
  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      placeholder: "Describe the expected behaviour"

  - type: input
    id: browser
    attributes:
      label: Browser and OS
      placeholder: "Firefox 124 on Ubuntu 22.04"

  - type: checkboxes
    id: checked
    attributes:
      label: Before submitting...
      options:
        - label: I've searched open issues
        - label: I'm happy to contribute a fix