name: Bug report
description: Report something that isn't working as expected on the SAHO website
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Bug Report — Help Us Improve!
        
        Thank you for taking the time to report an issue with South African History Online. Your attention to detail helps us create a better experience for everyone learning about South African history.
        
        **Everyone can help fix bugs** - whether you're reporting, testing, documenting, or coding!

  - type: input
    id: url
    attributes:
      label: URL (if applicable)
      description: Link to the affected page
      placeholder: "https://www.sahistory.org.za/page/example"

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
  
  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      placeholder: "Describe the expected behaviour"

  - type: input
    id: browser
    attributes:
      label: Browser and OS
      placeholder: "Firefox 124 on Ubuntu 22.04"

  - type: dropdown
    id: contribution_interest
    attributes:
      label: Would you like to help address this bug?
      description: There are many ways to contribute beyond coding!
      options:
        - No, just reporting
        - Yes, I can help test fixes
        - Yes, I can help document the solution
        - Yes, I can help implement a fix
        - Yes, I can help in another way (please specify below)
    validations:
      required: true

  - type: textarea
    id: contribution_details
    attributes:
      label: How would you like to help? (Optional)
      description: If you selected "Yes" above, please tell us how you'd like to help
      placeholder: "I can help by..."

  - type: markdown
    attributes:
      value: |
        ## Next Steps
        
        After submitting your bug report:
        
        1. The team will review and prioritize the issue
        2. We may ask for additional information to help reproduce the bug
        3. If you've offered to help, we'll coordinate with you on next steps
        
        **See our [Contribution Guide](../contribution_guide) for more ways to get involved!**

  - type: checkboxes
    id: checked
    attributes:
      label: Before submitting
      options:
        - label: I've searched for similar open issues
          required: true