name: Contribution Ideas
description: Share how you'd like to contribute to South African History Online
title: "[Contribution]: "
labels: ["contribution"]
body:
  - type: markdown
    attributes:
      value: |
        # 🌍 Join the SAHO Community!
        
        Thank you for your interest in contributing to South African History Online! We welcome contributions from people with diverse skills and backgrounds. You don't need to be a developer to make a meaningful impact.
        
        ## Ways to Contribute Beyond Code
        
        - **📚 Historical Research**: Help research and verify historical facts
        - **✍️ Content Creation**: Write or improve articles on South African history
        - **🔍 Fact Checking**: Review existing content for accuracy
        - **🌐 Translation**: Help translate content into South Africa's official languages
        - **🎨 Design**: Suggest UI/UX improvements or create graphics
        - **📋 Documentation**: Improve guides, tutorials, or help pages
        - **🧪 Testing**: Test the website and report usability issues
        - **🔊 Outreach**: Help promote SAHO in educational settings
        - **📊 Data**: Help with data collection, organization, or visualization
        - **📱 Accessibility**: Suggest improvements for users with disabilities

  - type: dropdown
    id: contribution_type
    attributes:
      label: Type of Contribution
      description: What area would you like to contribute to?
      options:
        - Historical Research
        - Content Creation
        - Fact Checking
        - Translation
        - Design
        - Documentation
        - Testing
        - Outreach
        - Data
        - Accessibility
        - Technical Development
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    id: contribution_details
    attributes:
      label: Tell us about your contribution idea
      description: Describe how you'd like to contribute and what impact you hope to make
      placeholder: "I'd like to contribute by..."
    validations:
      required: true

  - type: textarea
    id: expertise
    attributes:
      label: Your expertise or background
      description: Share any relevant experience or skills you bring (no expertise required!)
      placeholder: "I have experience with..."

  - type: textarea
    id: resources
    attributes:
      label: Resources or support needed
      description: What would help you make this contribution successfully?
      placeholder: "I would need..."

  - type: markdown
    attributes:
      value: |
        ## Next Steps
        
        After submitting this form:
        
        1. A team member will review your contribution idea
        2. We'll reach out to discuss how to proceed
        3. You'll be connected with relevant team members
        4. We'll provide guidance and resources to help you succeed
        
        **Every contribution matters!** Whether big or small, your input helps preserve and share South African history with the world.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contributor guidelines
      options:
        - label: I agree to follow the SAHO community guidelines and code of conduct
          required: true
        - label: I understand that my contributions will be under the project's license
          required: true