name: Feature request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "## ✨ Feature Request"

  - type: textarea
    id: motivation
    attributes:
      label: What's the motivation or problem?
      placeholder: "It would be great if users could export citations..."

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "Add an 'Export to RIS' button next to each citation block..."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "Users can manually paste into Mendeley, but it's slow."

  - type: textarea
    id: references
    attributes:
      label: Related examples or screenshots
      placeholder: "Attach images, or link to similar features on other sites."

  - type: checkboxes
    id: confirm
    attributes:
      label: Project Contribution
      options:
        - label: I've searched for similar issues
        - label: I'd like to help build this feature