name: Feature request
description: Suggest a new feature or enhancement for the SAHO website
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # ✨ Feature Request
        
        Thank you for helping improve South African History Online! Your ideas help us better preserve and share South African history with the world.
        
        **Everyone can contribute** to bringing new features to life - whether you're a developer, historian, educator, designer, or enthusiast!

  - type: textarea
    id: motivation
    attributes:
      label: What's the motivation or problem?
      placeholder: "It would be great if users could export citations..."

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "Add an 'Export to RIS' button next to each citation block..."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "Users can manually paste into Mendeley, but it's slow."

  - type: textarea
    id: references
    attributes:
      label: Related examples or screenshots
      placeholder: "Attach images, or link to similar features on other sites."

  - type: dropdown
    id: contribution_interest
    attributes:
      label: Would you like to help with this feature?
      description: There are many ways to contribute beyond coding!
      options:
        - No, just suggesting
        - Yes, I can help with design/mockups
        - Yes, I can help with content/writing
        - Yes, I can help with testing
        - Yes, I can help with development
        - Yes, I can help with research
        - Yes, I can help in another way (please specify below)
    validations:
      required: true

  - type: textarea
    id: contribution_details
    attributes:
      label: How would you like to contribute? (Optional)
      description: If you selected "Yes" above, please tell us how you'd like to help
      placeholder: "I can help by..."

  - type: markdown
    attributes:
      value: |
        ## Next Steps
        
        After submitting your feature request:
        
        1. The team will review and prioritize your suggestion
        2. We may reach out with questions or to discuss implementation
        3. If you've offered to help, we'll coordinate with you on next steps
        
        **See our [Contribution Guide](../contribution_guide) for more ways to get involved!**

  - type: checkboxes
    id: confirm
    attributes:
      label: Before submitting
      options:
        - label: I've searched for similar feature requests
          required: true