<?php

/**
 * @file
 * South African Provinces module file.
 */

/**
 * Implements hook_theme().
 */
function sa_provinces_theme($existing, $type, $theme, $path) {
  return [
    'sa_provinces_block' => [
      'variables' => [
        'provinces' => [],
        'block_title' => NULL,
        'intro_text' => NULL,
        'display_mode' => 'grid',
        'show_place_count' => TRUE,
        'show_featured_place' => TRUE,
      ],
      'template' => 'sa-provinces-block',
    ],
  ];
}
