<?php

/**
 * @file
 * This is a Drupal 10 settings.ddev.php file automatically generated by DDEV.
 *
 * DDEV manages this file and may delete or overwrite it unless this
 * comment, marked with #ddev-generated, is removed. It is recommended
 * that you leave this file alone.
 */

$host = "db";
$port = 3306;
$driver = "mysql";

$databases['default']['default']['database'] = "db";
$databases['default']['default']['username'] = "db";
$databases['default']['default']['password'] = "db";
$databases['default']['default']['host'] = $host;
$databases['default']['default']['port'] = $port;
$databases['default']['default']['driver'] = $driver;

$settings['hash_salt'] = '51cb29294a6425bac141bc2a6739f3393dfbb41d5dc1d91b75d07b86906b62cd';

// Recommended setting for Drupal 10 only
$settings['state_cache'] = TRUE;

// This will prevent Drupal from setting read-only permissions on sites/default.
$settings['skip_permissions_hardening'] = TRUE;

// This will ensure the site can only be accessed through the intended host
// names. Additional host patterns can be added for custom configurations.
$settings['trusted_host_patterns'] = ['.*'];

// Don't use Symfony's APCLoader. ddev includes APCu; Composer's APCu loader has
// better performance.
$settings['class_loader_auto_detect'] = FALSE;

// Set $settings['config_sync_directory'] if not set in settings.php.
if (empty($settings['config_sync_directory'])) {
  $settings['config_sync_directory'] = '../config/sync';
}

// Override drupal/symfony_mailer default config to use Mailpit.
$config['symfony_mailer.settings']['default_transport'] = 'sendmail';
$config['symfony_mailer.mailer_transport.sendmail']['plugin'] = 'smtp';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['user'] = '';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['pass'] = '';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['host'] = 'localhost';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['port'] = '1025';

// ============================================
// DEVELOPMENT OVERRIDES
// ============================================
// These settings override production optimizations for local development.

// Enable verbose logging for errors.
// https://www.drupal.org/forum/support/post-installation/2018-07-18/enable-drupal-8-backend-errorlogdebugging-mode
$config['system.logging']['error_level'] = 'verbose';

// Database log settings - keep more messages for debugging
$config['dblog.settings']['row_limit'] = 10000;

// Disable caching for development
$config['system.performance']['cache']['page']['max_age'] = 0;
$config['system.performance']['css']['preprocess'] = FALSE;
$config['system.performance']['js']['preprocess'] = FALSE;

// Enable development modules
$config['core.extension']['module']['devel'] = 1;
$config['core.extension']['module']['views_ui'] = 1;
$config['core.extension']['module']['field_ui'] = 1;
$config['core.extension']['module']['dblog'] = 1;

// Enable Twig debugging for theme development
$settings['twig_debug'] = TRUE;
$settings['twig_auto_reload'] = TRUE;
$settings['twig_cache'] = FALSE;

// PHP settings for development
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
ini_set('max_execution_time', 300); // 5 minutes for debugging
ini_set('memory_limit', '512M'); // More memory for development

// Disable secure cookies for local development (no HTTPS)
ini_set('session.cookie_secure', 0);

// Disable cache for better debugging - use memory backend instead of null
$settings['cache']['bins']['render'] = 'cache.backend.memory';
$settings['cache']['bins']['page'] = 'cache.backend.memory';
$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.memory';

// Redis configuration.
if (extension_loaded('redis') && !empty(getenv('REDIS_HOST'))) {
  $settings['redis.connection']['interface'] = 'PhpRedis';
  $settings['redis.connection']['host'] = getenv('REDIS_HOST');
  $settings['redis.connection']['port'] = getenv('REDIS_PORT') ?: '6379';
  $settings['cache']['default'] = 'cache.backend.redis';
  $settings['cache_prefix'] = 'd10_redis_';
}

// ============================================
// SEARCH API / SOLR CONFIGURATION
// ============================================
// Enable local Solr server for DDEV.
$config['search_api.server.local_solr']['status'] = TRUE;
$config['search_api.server.local_solr']['backend_config']['connector'] = 'solr_cloud_basic_auth';
$config['search_api.server.local_solr']['backend_config']['connector_config'] = [
  'scheme' => 'http',
  'host' => 'solr',
  'port' => 8983,
  'path' => '/',
  'core' => 'sahistory_content',
  'timeout' => 5,
  'index_timeout' => 5,
  'optimize_timeout' => 10,
  'finalize_timeout' => 30,
  'commit_within' => 1000,
  'username' => 'solr',
  'password' => 'SolrRocks',
];

// Disable production Solr server in DDEV.
$config['search_api.server.saho_prod']['status'] = FALSE;

// Enable and configure the main search index for local development.
// The view uses saho_content, so we point it to local_solr for DDEV.
$config['search_api.index.saho_content']['status'] = TRUE;
$config['search_api.index.saho_content']['server'] = 'local_solr';

// Also enable the DDEV-specific index (optional, for testing).
$config['search_api.index.saho_global_ddev']['status'] = TRUE;
