admin_emails: "info@sahistory.org.za\r\nchadrossouw@gmail.com"
admin:
  subject: 'New order placed'
  body: "Hi, \r\n An order was placed by [node:title] [basic_cart_order:basic_cart_email]\r\nSee the full order <a href=\"https://www.sahistory.org.za/admin/basic-cart-orders\">here</a>\r\nOrdered products:\r\n[basic_cart_order:products]\r\nTotal price: [basic_cart_order:basic_cart_total_price]"
send_emailto_user: 1
user:
  subject: 'New order placed'
  body: "Hi,\r\nYou just placed an order on the website [site:name]. Here are the order details:\r\n[basic_cart_order:products]\r\nTotal price: [basic_cart_order:basic_cart_total_price]\r\nWe will contact you as soon as possible."
thankyou:
  title: 'Thank you'
  text: "Thank you for placing an order on our website.\r\nWe will contact you as soon as possible."
  custom_page: thankyou
langcode: en
_core:
  default_config_hash: lYpjloaOj5NEmiAYwYNGLw5G33JbBer7N9REXZGINY8
