cart_page_title: 'Your Shopping Cart'
empty_cart: 'Your cart is empty'
cart_block_title: 'Your Cart'
view_cart_button: 'View Cart'
cart_update_button: Update
cart_updated_message: 'Shopping Cart Updated'
quantity_status: 1
quantity_label: Quantity
price_status: 1
price_label: Price
total_price_status: 1
total_price_label: 'Total Price'
currency_status: 1
currency: R
price_format: '4'
vat_state: 0
vat_value: !!float 0
add_to_cart_button: 'Add to cart'
add_to_cart_redirect: '<none>'
content_type:
  product: product
  archive: '0'
  article: '0'
  biography: '0'
  blog: '0'
  book: '0'
  button: '0'
  drag_and_drop_page: '0'
  event: '0'
  forum: '0'
  frontpagecustom: '0'
  image: '0'
  landing_page_banners: '0'
  newsletter: '0'
  node_gallery_gallery: '0'
  node_gallery_item: '0'
  page: '0'
  panel: '0'
  place: '0'
  pmticket: '0'
  pmtimetracking: '0'
  product_kit: '0'
  upcomingevent: '0'
  webform: '0'
order_status: 1
langcode: en
added_to_cart_message: 'Added to cart'
use_cart_table: 0
_core:
  default_config_hash: IXDTctH9JHSwy-Ca3y24Us3CuYVr4mVbfP1eTnXKFzU
placeorder_button_name: 'Place Order'
cart_button_name: Checkout
