palette:
  base: '#b30909'
  link: '#b30909'
  accent1: '#b30909'
  accent2: '#b30909'
  text: '#202220'
  headings: '#b30909'
  footer: '#fff'
  footertext: '#b30909'
  secheader: '#fff'
  secheadertext: '#b30909'
  well: '#eeeeee'
  welltext: '#444444'
  header: '#ffffff'
  headertext: '#696969'
  headerside: '#20252a'
  headersidetext: '#737a85'
  pagetitle: '#fff'
  pagetitletext: '#b30909'
  graylight: '#777777'
  graylighter: '#ededed'
  silver: '#f1f1f1'
  body: '#fff'
logo: 'public://color/glazed_saho-9b685249/logo.svg'
stylesheets:
  - 'public://color/glazed_saho-9b685249/glazed.css'
files:
  - 'public://color/glazed_saho-9b685249/logo.svg'
  - 'public://color/glazed_saho-9b685249/glazed-favicon.png'
  - 'public://color/glazed_saho-9b685249/glazed.css'
