palette:
  top: '#e6e6e6'
  bottom: '#2c2c2c'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#990000'
logo: 'public://color/bartik-e91f1526/logo.png'
stylesheets:
  - 'public://color/bartik-e91f1526/colors.css'
files:
  - 'public://color/bartik-e91f1526/logo.png'
  - 'public://color/bartik-e91f1526/colors.css'
