favicon:
  mimetype: image/vnd.microsoft.icon
  path: favicon.ico
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  name: true
  node_user_picture: true
  slogan: true
logo:
  path: ''
  use_default: true
third_party_settings:
  shortcut:
    module_link: true
