log:
  level: INFO

global:
  checkNewVersion: false
  sendAnonymousUsage: false

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        options: "mintls12@file"

  traefik:
    address: ":8042"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yaml"
    watch: true

api:
  insecure: true
  dashboard: true

ping:

accessLog:
  filePath: "/etc/traefik/access.log"
  bufferingSize: 100
  filters:
    statusCodes: "400-499"

serversTransport:
  insecureSkipVerify: true
