#!/bin/bash

## Description: Run PHPUnit tests for custom modules
## Usage: phpunit [options]
## Example: "ddev phpunit --testsuite unit" or "ddev phpunit --filter TermTrackerTest"

cd /var/www/html/webroot/modules/custom
../../../vendor/bin/phpunit --configuration phpunit.xml "$@"
