<?php

/**
 * @file
 * Contains layout_builder_fix.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function layout_builder_fix_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.layout_builder_fix':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Fixes the LoggerInterface issue in Layout Builder after Drupal 11 update.') . '</p>';
      return $output;
  }
}