block.settings.register_grid_block:
  type: block_settings
  label: 'Register grid block settings'
  mapping:
    register:
      type: string
      label: 'Register (data source)'
    subset:
      type: string
      label: 'Subset of the register'
    block_title:
      type: label
      label: 'Heading'
    intro_text:
      type: text
      label: 'Standfirst'
    display_mode:
      type: string
      label: 'Layout (grid or list)'
    show_count:
      type: boolean
      label: 'Show record counts'
    show_featured:
      type: boolean
      label: 'Show the featured record'
