# Schema for the configuration files of the uc_payfast module.

uc_payfast.settings:
  type: config_object
  label: 'PayFast settings'
  mapping:
    merchant_id:
      type: string
      label: 'PayFast Merchant ID'
    merchant_key:
      type: string
      label: 'PayFast Merchant Key'
    passphrase:
      type: string
      label: 'PayFast Passphrase'
    server:
      type: boolean
      label: 'Sandbox/Test mode'
