<?php

/**
 * @file
 * Primary module hooks for SAHO Upcoming Events module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function saho_upcoming_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.saho_upcoming_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The SAHO Upcoming Events module provides functionality to display upcoming events on the front page.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function saho_upcoming_events_theme() {
  return [
    'saho_upcoming_events_block' => [
      'variables' => [
        'events' => [],
        'config' => [],
      ],
      'template' => 'saho-upcoming-events-block',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for views_view.
 */
function saho_upcoming_events_preprocess_views_view(&$variables) {
  $view = $variables['view'];
  
  // Add CSS for all upcoming events view.
  if ($view->id() == 'all_upcoming_events') {
    $variables['#attached']['library'][] = 'saho_upcoming_events/upcoming_events';
  }
}
